# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cc5e6a94506dcaa0136bc27ead0187733cdebbf21b2900720a78270012cfd97e81517a4668100f7c0cdf2ad19fc5e9da16cd0b0dde311f48a354fb968e0e46

test:
  secret_key_base: 5afc7119b0fc4ba0a4c8b9f459d52ca620dc30d53058455bf129b171c77add5ba1ae037f407a97bdc9c8db050740f43139fbc84813c1f9372dd87ede29835d65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
